### ISSUE TITLE
DeprecationWarning: please use dns.resolver.resolve() instead

### ISSUE THREAD

**Issue by adelerhof** [jeromba6/certbot_transip_helper#2]
The command certbot_transip_helper.py throws a DeprecationWarning:
`DeprecationWarning: please use dns.resolver.resolve() instead`

When line 88 is changed from:

```python
res = str(dns.resolver.query(acme_entry + '.' + certbot_domain, "TXT").response.answer[0][-1]).replace('"','')
```

to:

```python
res = str(dns.resolver.resolve(acme_entry + '.' + certbot_domain, "TXT").response.answer[0][-1]).replace('"','')
```

It still throws an error: `Checking for DNS change succesfull failed.` (Nice message BTW)
The TXT record is still created, it seems the lookup/filter fails.
Meetup to fix this together?

Entry for _acme-challenge.blaataap.com created
Waiting for getting succesfull DNS result: ....................................................................................................
Checking for DNS change succesfull failed.

```bash
manual-auth-hook command "/home/blaataap/blaataap.com/certbot_transip_helper/certbot_transip_helper.py" returned error code 1
Error output from manual-auth-hook command certbot_transip_helper.py:
/home/blaataap/blaataap.com/certbot_transip_helper/certbot_transip_helper.py:88: DeprecationWarning: please use dns.resolver.resolve() instead
  res = str(dns.resolver.query(acme_entry + '.' + certbot_domain, "TXT").response.answer[0][-1]).replace('"','')
```

**Comment by jeromba6** [comment]
I can't reproduce your issue, so maybe look in to it together.

**Comment by adelerhof** [comment]
Fixed in https://github.com/jeromba6/certbot_transip_helper/commit/f0437831844c9b85b7c68517243a9ef432a0b109
Thanks a lot for the effort!
