### ISSUE TITLE
Het is stuk op een gegeven moment

### ISSUE THREAD

**Issue by adelerhof** [jeromba6/certbot_transip_helper#5]
Het certbot script blijft in een oneindige loop hangen.
Het maakt een TXT record aan, maar de lookup/verificatie gebeurd niet.

**Comment by jeromba6** [comment]
Hoe dan?

**Comment by jeromba6** [comment]
Aanpassingen aan README.md zouden je probleem moeten verhelpen.

**Comment by adelerhof** [comment]
Werkt weer! Dank
